const password = '$2b$10$wH9BWiv/VS0HjuYx9CVmLu85sKMfuPC6LaFhzuEBuwIUx9oc8moai';

exports.users = [
  {
    id: 1,
    username: 'teemu',
    password,
    first_name: 'teemu',
    last_name: 'kostamo',
    email: 'teemu@kostamo.com',
    address: null,
    zip: null,
    city: null,
    country: null,
    phone: null,
    status: 1,
    level: 3,
    last_seen: '2020-10-26 16:54:57',
    reset_key: null,
    old_id: null,
  },
  {
    id: 2,
    username: 'darude',
    password,
    first_name: 'da',
    last_name: 'rude',
    email: 'sand@storm.com',
    address: null,
    zip: null,
    city: null,
    country: null,
    phone: null,
    status: 1,
    level: 3,
    last_seen: '2020-10-25 16:54:57',
    reset_key: null,
    old_id: null,
  },
  {
    id: 3,
    username: 'jack',
    password,
    first_name: 'jack',
    last_name: 'bauer',
    email: 'bauer@ctu.com',
    address: null,
    zip: null,
    city: null,
    country: null,
    phone: null,
    status: 1,
    level: 3,
    last_seen: '2020-10-26 16:54:57',
    reset_key: null,
    old_id: null,
  },
];
